name: Release Foundry VTT Package

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release with unique tag
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: |
            module.json
            module-zip.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update ‘latest’ tag to point to newest release
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch --tags
          # Forcer la création ou mise à jour du tag 'latest' vers la nouvelle release
          git tag -f latest v${{ github.run_number }}
          git push -f origin latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
