name: Release Foundry VTT Package

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Release avec tag unique
      - name: Create release with unique tag
        id: release_unique
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: |
            module.json
            module-zip.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Release avec tag 'latest'
      - name: Create release with latest tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest release
          files: |
            module.json
            module-zip.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
