name: Auto Release on Commit

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.sha }}
          tag_name: ${{ github.sha }}
          files: |
            ./module-zip.txt
            ./module.json

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
